// Code generated by ogen, DO NOT EDIT.

package api

import (
	"math/bits"
	"strconv"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/validate"
)

// Encode implements json.Marshaler.
func (s *ExchangeToken4XX) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ExchangeToken4XX) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("error")
		s.Error.Encode(e)
	}
	{
		if s.ErrorDescription.Set {
			e.FieldStart("error_description")
			s.ErrorDescription.Encode(e)
		}
	}
	{
		if s.ErrorURI.Set {
			e.FieldStart("error_uri")
			s.ErrorURI.Encode(e)
		}
	}
}

var jsonFieldsNameOfExchangeToken4XX = [3]string{
	0: "error",
	1: "error_description",
	2: "error_uri",
}

// Decode decodes ExchangeToken4XX from json.
func (s *ExchangeToken4XX) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExchangeToken4XX to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "error":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.Error.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"error\"")
			}
		case "error_description":
			if err := func() error {
				s.ErrorDescription.Reset()
				if err := s.ErrorDescription.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"error_description\"")
			}
		case "error_uri":
			if err := func() error {
				s.ErrorURI.Reset()
				if err := s.ErrorURI.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"error_uri\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ExchangeToken4XX")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfExchangeToken4XX) {
					name = jsonFieldsNameOfExchangeToken4XX[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ExchangeToken4XX) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExchangeToken4XX) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes ExchangeToken4XXError as json.
func (s ExchangeToken4XXError) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes ExchangeToken4XXError from json.
func (s *ExchangeToken4XXError) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExchangeToken4XXError to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch ExchangeToken4XXError(v) {
	case ExchangeToken4XXErrorInvalidRequest:
		*s = ExchangeToken4XXErrorInvalidRequest
	case ExchangeToken4XXErrorInvalidScope:
		*s = ExchangeToken4XXErrorInvalidScope
	case ExchangeToken4XXErrorInvalidTarget:
		*s = ExchangeToken4XXErrorInvalidTarget
	default:
		*s = ExchangeToken4XXError(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s ExchangeToken4XXError) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExchangeToken4XXError) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ExchangeTokenOK) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ExchangeTokenOK) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("access_token")
		e.Str(s.AccessToken)
	}
	{
		e.FieldStart("issued_token_type")
		s.IssuedTokenType.Encode(e)
	}
	{
		e.FieldStart("token_type")
		s.TokenType.Encode(e)
	}
	{
		e.FieldStart("expires_in")
		e.Float64(s.ExpiresIn)
	}
}

var jsonFieldsNameOfExchangeTokenOK = [4]string{
	0: "access_token",
	1: "issued_token_type",
	2: "token_type",
	3: "expires_in",
}

// Decode decodes ExchangeTokenOK from json.
func (s *ExchangeTokenOK) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExchangeTokenOK to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "access_token":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Str()
				s.AccessToken = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"access_token\"")
			}
		case "issued_token_type":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				if err := s.IssuedTokenType.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"issued_token_type\"")
			}
		case "token_type":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				if err := s.TokenType.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"token_type\"")
			}
		case "expires_in":
			requiredBitSet[0] |= 1 << 3
			if err := func() error {
				v, err := d.Float64()
				s.ExpiresIn = float64(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"expires_in\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ExchangeTokenOK")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00001111,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfExchangeTokenOK) {
					name = jsonFieldsNameOfExchangeTokenOK[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ExchangeTokenOK) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExchangeTokenOK) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes ExchangeTokenOKIssuedTokenType as json.
func (s ExchangeTokenOKIssuedTokenType) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes ExchangeTokenOKIssuedTokenType from json.
func (s *ExchangeTokenOKIssuedTokenType) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExchangeTokenOKIssuedTokenType to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch ExchangeTokenOKIssuedTokenType(v) {
	case ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt:
		*s = ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt
	default:
		*s = ExchangeTokenOKIssuedTokenType(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s ExchangeTokenOKIssuedTokenType) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExchangeTokenOKIssuedTokenType) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes ExchangeTokenOKTokenType as json.
func (s ExchangeTokenOKTokenType) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes ExchangeTokenOKTokenType from json.
func (s *ExchangeTokenOKTokenType) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExchangeTokenOKTokenType to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch ExchangeTokenOKTokenType(v) {
	case ExchangeTokenOKTokenTypeBearer:
		*s = ExchangeTokenOKTokenTypeBearer
	default:
		*s = ExchangeTokenOKTokenType(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s ExchangeTokenOKTokenType) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExchangeTokenOKTokenType) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptString to nil")
	}
	o.Set = true
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
