// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s *ExchangeToken4XX) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Error.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "error",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ExchangeToken4XXError) Validate() error {
	switch s {
	case "invalid_request":
		return nil
	case "invalid_scope":
		return nil
	case "invalid_target":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ExchangeToken4XXStatusCode) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ExchangeTokenOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.IssuedTokenType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "issued_token_type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.TokenType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "token_type",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.ExpiresIn)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "expires_in",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ExchangeTokenOKIssuedTokenType) Validate() error {
	switch s {
	case "urn:ietf:params:oauth:grant-type:jwt":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ExchangeTokenOKTokenType) Validate() error {
	switch s {
	case "Bearer":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TokenExchangeRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.GrantType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "grant_type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.SubjectTokenType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "subject_token_type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TokenExchangeRequestGrantType) Validate() error {
	switch s {
	case "urn:ietf:params:oauth:grant-type:token-exchange":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s TokenExchangeRequestSubjectTokenType) Validate() error {
	switch s {
	case "urn:ietf:params:oauth:grant-type:id_token":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
