// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

type ExchangeToken4XX struct {
	Error            ExchangeToken4XXError `json:"error"`
	ErrorDescription OptString             `json:"error_description"`
	ErrorURI         OptString             `json:"error_uri"`
}

// GetError returns the value of Error.
func (s *ExchangeToken4XX) GetError() ExchangeToken4XXError {
	return s.Error
}

// GetErrorDescription returns the value of ErrorDescription.
func (s *ExchangeToken4XX) GetErrorDescription() OptString {
	return s.ErrorDescription
}

// GetErrorURI returns the value of ErrorURI.
func (s *ExchangeToken4XX) GetErrorURI() OptString {
	return s.ErrorURI
}

// SetError sets the value of Error.
func (s *ExchangeToken4XX) SetError(val ExchangeToken4XXError) {
	s.Error = val
}

// SetErrorDescription sets the value of ErrorDescription.
func (s *ExchangeToken4XX) SetErrorDescription(val OptString) {
	s.ErrorDescription = val
}

// SetErrorURI sets the value of ErrorURI.
func (s *ExchangeToken4XX) SetErrorURI(val OptString) {
	s.ErrorURI = val
}

type ExchangeToken4XXError string

const (
	ExchangeToken4XXErrorInvalidRequest ExchangeToken4XXError = "invalid_request"
	ExchangeToken4XXErrorInvalidScope   ExchangeToken4XXError = "invalid_scope"
	ExchangeToken4XXErrorInvalidTarget  ExchangeToken4XXError = "invalid_target"
)

// AllValues returns all ExchangeToken4XXError values.
func (ExchangeToken4XXError) AllValues() []ExchangeToken4XXError {
	return []ExchangeToken4XXError{
		ExchangeToken4XXErrorInvalidRequest,
		ExchangeToken4XXErrorInvalidScope,
		ExchangeToken4XXErrorInvalidTarget,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExchangeToken4XXError) MarshalText() ([]byte, error) {
	switch s {
	case ExchangeToken4XXErrorInvalidRequest:
		return []byte(s), nil
	case ExchangeToken4XXErrorInvalidScope:
		return []byte(s), nil
	case ExchangeToken4XXErrorInvalidTarget:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExchangeToken4XXError) UnmarshalText(data []byte) error {
	switch ExchangeToken4XXError(data) {
	case ExchangeToken4XXErrorInvalidRequest:
		*s = ExchangeToken4XXErrorInvalidRequest
		return nil
	case ExchangeToken4XXErrorInvalidScope:
		*s = ExchangeToken4XXErrorInvalidScope
		return nil
	case ExchangeToken4XXErrorInvalidTarget:
		*s = ExchangeToken4XXErrorInvalidTarget
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ExchangeToken4XXStatusCode wraps ExchangeToken4XX with StatusCode.
type ExchangeToken4XXStatusCode struct {
	StatusCode int
	Response   ExchangeToken4XX
}

// GetStatusCode returns the value of StatusCode.
func (s *ExchangeToken4XXStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ExchangeToken4XXStatusCode) GetResponse() ExchangeToken4XX {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ExchangeToken4XXStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ExchangeToken4XXStatusCode) SetResponse(val ExchangeToken4XX) {
	s.Response = val
}

func (*ExchangeToken4XXStatusCode) exchangeTokenRes() {}

type ExchangeTokenOK struct {
	AccessToken     string                         `json:"access_token"`
	IssuedTokenType ExchangeTokenOKIssuedTokenType `json:"issued_token_type"`
	TokenType       ExchangeTokenOKTokenType       `json:"token_type"`
	ExpiresIn       float64                        `json:"expires_in"`
}

// GetAccessToken returns the value of AccessToken.
func (s *ExchangeTokenOK) GetAccessToken() string {
	return s.AccessToken
}

// GetIssuedTokenType returns the value of IssuedTokenType.
func (s *ExchangeTokenOK) GetIssuedTokenType() ExchangeTokenOKIssuedTokenType {
	return s.IssuedTokenType
}

// GetTokenType returns the value of TokenType.
func (s *ExchangeTokenOK) GetTokenType() ExchangeTokenOKTokenType {
	return s.TokenType
}

// GetExpiresIn returns the value of ExpiresIn.
func (s *ExchangeTokenOK) GetExpiresIn() float64 {
	return s.ExpiresIn
}

// SetAccessToken sets the value of AccessToken.
func (s *ExchangeTokenOK) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetIssuedTokenType sets the value of IssuedTokenType.
func (s *ExchangeTokenOK) SetIssuedTokenType(val ExchangeTokenOKIssuedTokenType) {
	s.IssuedTokenType = val
}

// SetTokenType sets the value of TokenType.
func (s *ExchangeTokenOK) SetTokenType(val ExchangeTokenOKTokenType) {
	s.TokenType = val
}

// SetExpiresIn sets the value of ExpiresIn.
func (s *ExchangeTokenOK) SetExpiresIn(val float64) {
	s.ExpiresIn = val
}

func (*ExchangeTokenOK) exchangeTokenRes() {}

type ExchangeTokenOKIssuedTokenType string

const (
	ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt ExchangeTokenOKIssuedTokenType = "urn:ietf:params:oauth:grant-type:jwt"
)

// AllValues returns all ExchangeTokenOKIssuedTokenType values.
func (ExchangeTokenOKIssuedTokenType) AllValues() []ExchangeTokenOKIssuedTokenType {
	return []ExchangeTokenOKIssuedTokenType{
		ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExchangeTokenOKIssuedTokenType) MarshalText() ([]byte, error) {
	switch s {
	case ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExchangeTokenOKIssuedTokenType) UnmarshalText(data []byte) error {
	switch ExchangeTokenOKIssuedTokenType(data) {
	case ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt:
		*s = ExchangeTokenOKIssuedTokenTypeUrnIetfParamsOAuthGrantTypeJwt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ExchangeTokenOKTokenType string

const (
	ExchangeTokenOKTokenTypeBearer ExchangeTokenOKTokenType = "Bearer"
)

// AllValues returns all ExchangeTokenOKTokenType values.
func (ExchangeTokenOKTokenType) AllValues() []ExchangeTokenOKTokenType {
	return []ExchangeTokenOKTokenType{
		ExchangeTokenOKTokenTypeBearer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExchangeTokenOKTokenType) MarshalText() ([]byte, error) {
	switch s {
	case ExchangeTokenOKTokenTypeBearer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExchangeTokenOKTokenType) UnmarshalText(data []byte) error {
	switch ExchangeTokenOKTokenType(data) {
	case ExchangeTokenOKTokenTypeBearer:
		*s = ExchangeTokenOKTokenTypeBearer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/TokenExchangeRequest
type TokenExchangeRequest struct {
	GrantType        TokenExchangeRequestGrantType        `json:"grant_type"`
	Audience         []string                             `json:"audience"`
	Scope            OptString                            `json:"scope"`
	SubjectToken     string                               `json:"subject_token"`
	SubjectTokenType TokenExchangeRequestSubjectTokenType `json:"subject_token_type"`
}

// GetGrantType returns the value of GrantType.
func (s *TokenExchangeRequest) GetGrantType() TokenExchangeRequestGrantType {
	return s.GrantType
}

// GetAudience returns the value of Audience.
func (s *TokenExchangeRequest) GetAudience() []string {
	return s.Audience
}

// GetScope returns the value of Scope.
func (s *TokenExchangeRequest) GetScope() OptString {
	return s.Scope
}

// GetSubjectToken returns the value of SubjectToken.
func (s *TokenExchangeRequest) GetSubjectToken() string {
	return s.SubjectToken
}

// GetSubjectTokenType returns the value of SubjectTokenType.
func (s *TokenExchangeRequest) GetSubjectTokenType() TokenExchangeRequestSubjectTokenType {
	return s.SubjectTokenType
}

// SetGrantType sets the value of GrantType.
func (s *TokenExchangeRequest) SetGrantType(val TokenExchangeRequestGrantType) {
	s.GrantType = val
}

// SetAudience sets the value of Audience.
func (s *TokenExchangeRequest) SetAudience(val []string) {
	s.Audience = val
}

// SetScope sets the value of Scope.
func (s *TokenExchangeRequest) SetScope(val OptString) {
	s.Scope = val
}

// SetSubjectToken sets the value of SubjectToken.
func (s *TokenExchangeRequest) SetSubjectToken(val string) {
	s.SubjectToken = val
}

// SetSubjectTokenType sets the value of SubjectTokenType.
func (s *TokenExchangeRequest) SetSubjectTokenType(val TokenExchangeRequestSubjectTokenType) {
	s.SubjectTokenType = val
}

type TokenExchangeRequestGrantType string

const (
	TokenExchangeRequestGrantTypeUrnIetfParamsOAuthGrantTypeTokenExchange TokenExchangeRequestGrantType = "urn:ietf:params:oauth:grant-type:token-exchange"
)

// AllValues returns all TokenExchangeRequestGrantType values.
func (TokenExchangeRequestGrantType) AllValues() []TokenExchangeRequestGrantType {
	return []TokenExchangeRequestGrantType{
		TokenExchangeRequestGrantTypeUrnIetfParamsOAuthGrantTypeTokenExchange,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TokenExchangeRequestGrantType) MarshalText() ([]byte, error) {
	switch s {
	case TokenExchangeRequestGrantTypeUrnIetfParamsOAuthGrantTypeTokenExchange:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TokenExchangeRequestGrantType) UnmarshalText(data []byte) error {
	switch TokenExchangeRequestGrantType(data) {
	case TokenExchangeRequestGrantTypeUrnIetfParamsOAuthGrantTypeTokenExchange:
		*s = TokenExchangeRequestGrantTypeUrnIetfParamsOAuthGrantTypeTokenExchange
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TokenExchangeRequestSubjectTokenType string

const (
	TokenExchangeRequestSubjectTokenTypeUrnIetfParamsOAuthGrantTypeIDToken TokenExchangeRequestSubjectTokenType = "urn:ietf:params:oauth:grant-type:id_token"
)

// AllValues returns all TokenExchangeRequestSubjectTokenType values.
func (TokenExchangeRequestSubjectTokenType) AllValues() []TokenExchangeRequestSubjectTokenType {
	return []TokenExchangeRequestSubjectTokenType{
		TokenExchangeRequestSubjectTokenTypeUrnIetfParamsOAuthGrantTypeIDToken,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TokenExchangeRequestSubjectTokenType) MarshalText() ([]byte, error) {
	switch s {
	case TokenExchangeRequestSubjectTokenTypeUrnIetfParamsOAuthGrantTypeIDToken:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TokenExchangeRequestSubjectTokenType) UnmarshalText(data []byte) error {
	switch TokenExchangeRequestSubjectTokenType(data) {
	case TokenExchangeRequestSubjectTokenTypeUrnIetfParamsOAuthGrantTypeIDToken:
		*s = TokenExchangeRequestSubjectTokenTypeUrnIetfParamsOAuthGrantTypeIDToken
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
